import type { Metadata } from "next";
import { LanguageProvider } from "./components/languageContext"; 
import Header from "./components/header";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
       <LanguageProvider>
      <body className="Gill_Sans">
      <Header />
        {children}
      </body>
      </LanguageProvider>
    </html>
  );
}
