import { Alfa_Slab_One, Alegreya_Sans_SC } from "next/font/google";
import "./globals.css";

const alfaSlabOne = Alfa_Slab_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: '--font-alfa-slab-one'
});

const alegreyaSansSC = Alegreya_Sans_SC({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "800","900"], 
  variable: '--font-alegreya-sans-sc'
});

export const metadata = {
  title: "Mttalento",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${alfaSlabOne.className} ${alegreyaSansSC.className}`}>
        {children}
      </body>
    </html>
  );
}
